version: "3"

services:
  traefik:
    container_name: "traefik"
    image: "traefik:1.7.16"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik.toml:/traefik.toml"
      - "./data/acme.json:/acme.json"
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.frontend.rule: "Host:YOUR_HOSTNAME_HERE"
      traefik.frontend.auth.basic.users: "" # Use http://www.htaccesstools.com/htpasswd-generator/

networks:
  traefik:
    external: "true"
